global:
  scrape_interval: 15s #consultation time and metrics acquisition
scrape_configs:
  - job_name: dice-service
    scrape_interval: 5s
    static_configs: 
      - targets: [dice-app-container:9464]


remote_write:
- url: http://grafana:3000
  basic_auth:
    username: admin
    password: admin